version: '3'

services:
    songbook:
        image: jekyll/jekyll
        command: jekyll serve
        volumes:
            - "./songbook/:/srv/jekyll"
            - "${CHORD_PATH}/:/srv/jekyll/_songs"
        ports:
            - "4000:4000"
