version: '3'

services:
    chord-compiler:
        image: jekyll/jekyll
        command: jekyll serve
        volumes:
            - "./chord-compiler/:/srv/jekyll"
            - "${CHORD_PATH}/:/srv/jekyll/_chords"
        ports:
            - "4000:4000"
