title: Chords
email: chords@frazerseymour.com
description: A Jekyll site for rendering Markdown lyrics and chords into pretty HTML.
baseurl: ""
url: "http://chords.frazerseymour.com"

# Build settings
markdown: kramdown
highlighter: none
collections:
    chords:
        output: true
defaults:
    -
        scope:
            path: ""
            type: "chords"
        values:
            layout: chordsheet
            title: "Song Title"
            artist: "Song Artist"
            album: "Song Album"
            link: https://open.spotify.com
            key: A
            capo: "-"
            tuning: EADGBE
exclude:
    - _chords/example.md
